import { Groups } from "./groups";
import { Teams } from "./teams";
import { TournamentStage, type Round } from "../types/tournament";

const normalize = (str: string) =>
  str
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .trim();

const teamMap = Object.fromEntries(Teams.map((t) => [normalize(t.name), t]));
const groupMap = Object.fromEntries(Groups.map((g) => [normalize(g.name), g]));

export const Round_One: Round = {
  id: 1,
  matches: [
    {
      id: 1,
      groupId: groupMap[normalize("Grupo A")]?.id,
      homeTeamId: { ...teamMap[normalize("México")] }.id,
      awayTeamId: { ...teamMap[normalize("África do Sul")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-11T16:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 1,
    },
    {
      id: 2,
      groupId: groupMap[normalize("Grupo A")]?.id,
      homeTeamId: { ...teamMap[normalize("Coréia do Sul")] }.id,
      awayTeamId: { ...teamMap[normalize("Republica Tcheca")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-11T23:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 1,
    },
    {
      id: 3,
      groupId: groupMap[normalize("Grupo B")]?.id,
      homeTeamId: { ...teamMap[normalize("Canadá")] }.id,
      awayTeamId: { ...teamMap[normalize("Bósnia e Herzegovina")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-12T16:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 1,
    },
    {
      id: 4,
      groupId: groupMap[normalize("Grupo B")]?.id,
      homeTeamId: { ...teamMap[normalize("Catar")] }.id,
      awayTeamId: { ...teamMap[normalize("Suíça")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-13T16:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 1,
    },
    {
      id: 5,
      groupId: groupMap[normalize("Grupo C")]?.id,
      homeTeamId: { ...teamMap[normalize("Brasil")] }.id,
      awayTeamId: { ...teamMap[normalize("Marrocos")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-13T19:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 1,
    },
    {
      id: 6,
      groupId: groupMap[normalize("Grupo C")]?.id,
      homeTeamId: { ...teamMap[normalize("Haiti")] }.id,
      awayTeamId: { ...teamMap[normalize("Escócia")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-13T22:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 1,
    },
    {
      id: 7,
      groupId: groupMap[normalize("Grupo D")]?.id,
      homeTeamId: { ...teamMap[normalize("Estados Unidos")] }.id,
      awayTeamId: { ...teamMap[normalize("Paraguai")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-12T22:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 1,
    },
    {
      id: 8,
      groupId: groupMap[normalize("Grupo D")]?.id,
      homeTeamId: { ...teamMap[normalize("Austrália")] }.id,
      awayTeamId: { ...teamMap[normalize("Turquia")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-14T01:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 1,
    },
    {
      id: 9,
      groupId: groupMap[normalize("Grupo E")]?.id,
      homeTeamId: { ...teamMap[normalize("Alemanha")] }.id,
      awayTeamId: { ...teamMap[normalize("Curaçao")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-14T14:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 1,
    },
    {
      id: 10,
      groupId: groupMap[normalize("Grupo E")]?.id,
      homeTeamId: { ...teamMap[normalize("Costa do Marfim")] }.id,
      awayTeamId: { ...teamMap[normalize("Equador")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-14T20:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 1,
    },
    {
      id: 11,
      groupId: groupMap[normalize("Grupo F")]?.id,
      homeTeamId: { ...teamMap[normalize("Holanda")] }.id,
      awayTeamId: { ...teamMap[normalize("Japão")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-14T17:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 1,
    },
    {
      id: 12,
      groupId: groupMap[normalize("Grupo F")]?.id,
      homeTeamId: { ...teamMap[normalize("Suécia")] }.id,
      awayTeamId: { ...teamMap[normalize("Tunísia")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-14T23:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 1,
    },
    {
      id: 13,
      groupId: groupMap[normalize("Grupo G")]?.id,
      homeTeamId: { ...teamMap[normalize("Bélgica")] }.id,
      awayTeamId: { ...teamMap[normalize("Egito")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-15T16:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 1,
    },
    {
      id: 14,
      groupId: groupMap[normalize("Grupo G")]?.id,
      homeTeamId: { ...teamMap[normalize("Iran")] }.id,
      awayTeamId: { ...teamMap[normalize("Nova Zelândia")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-15T22:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 1,
    },
    {
      id: 15,
      groupId: groupMap[normalize("Grupo H")]?.id,
      homeTeamId: { ...teamMap[normalize("Espanha")] }.id,
      awayTeamId: { ...teamMap[normalize("Cabo Verde")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-15T13:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 1,
    },
    {
      id: 16,
      groupId: groupMap[normalize("Grupo H")]?.id,
      homeTeamId: { ...teamMap[normalize("Arábia Saudita")] }.id,
      awayTeamId: { ...teamMap[normalize("Uruguai")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-15T19:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 1,
    },
    {
      id: 17,
      groupId: groupMap[normalize("Grupo I")]?.id,
      homeTeamId: { ...teamMap[normalize("França")] }.id,
      awayTeamId: { ...teamMap[normalize("Senegal")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-16T16:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 1,
    },
    {
      id: 18,
      groupId: groupMap[normalize("Grupo I")]?.id,
      homeTeamId: { ...teamMap[normalize("Iraque")] }.id,
      awayTeamId: { ...teamMap[normalize("Noruega")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-16T19:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 1,
    },
    {
      id: 19,
      groupId: groupMap[normalize("Grupo J")]?.id,
      homeTeamId: { ...teamMap[normalize("Argentina")] }.id,
      awayTeamId: { ...teamMap[normalize("Argélia")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-16T22:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 1,
    },
    {
      id: 20,
      groupId: groupMap[normalize("Grupo J")]?.id,
      homeTeamId: { ...teamMap[normalize("Áustria")] }.id,
      awayTeamId: { ...teamMap[normalize("Jordânia")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-17T01:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 1,
    },
    {
      id: 21,
      groupId: groupMap[normalize("Grupo K")]?.id,
      homeTeamId: { ...teamMap[normalize("Portugal")] }.id,
      awayTeamId: { ...teamMap[normalize("Congo")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-17T14:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 1,
    },
    {
      id: 22,
      groupId: groupMap[normalize("Grupo K")]?.id,
      homeTeamId: { ...teamMap[normalize("Uzbequistão")] }.id,
      awayTeamId: { ...teamMap[normalize("Colômbia")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-17T23:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 1,
    },
    {
      id: 23,
      groupId: groupMap[normalize("Grupo L")]?.id,
      homeTeamId: { ...teamMap[normalize("Inglaterra")] }.id,
      awayTeamId: { ...teamMap[normalize("Croácia")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-17T17:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 1,
    },
    {
      id: 24,
      groupId: groupMap[normalize("Grupo L")]?.id,
      homeTeamId: { ...teamMap[normalize("Gana")] }.id,
      awayTeamId: { ...teamMap[normalize("Panamá")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-17T20:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 1,
    },
  ],
};

export const Round_Two: Round = {
  id: 2,
  matches: [
    {
      id: 25,
      groupId: groupMap[normalize("Grupo A")]?.id,
      homeTeamId: { ...teamMap[normalize("República Tcheca")] }.id,
      awayTeamId: { ...teamMap[normalize("África do Sul")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-18T13:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 2,
    },
    {
      id: 26,
      groupId: groupMap[normalize("Grupo A")]?.id,
      homeTeamId: { ...teamMap[normalize("México")] }.id,
      awayTeamId: { ...teamMap[normalize("Coreia do Sul")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-18T22:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 2,
    },
    {
      id: 27,
      groupId: groupMap[normalize("Grupo B")]?.id,
      homeTeamId: { ...teamMap[normalize("Suíça")] }.id,
      awayTeamId: { ...teamMap[normalize("Bósnia e Herzegovina")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-18T16:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 2,
    },
    {
      id: 28,
      groupId: groupMap[normalize("Grupo B")]?.id,
      homeTeamId: { ...teamMap[normalize("Canadá")] }.id,
      awayTeamId: { ...teamMap[normalize("Catar")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-18T19:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 2,
    },
    {
      id: 29,
      groupId: groupMap[normalize("Grupo C")]?.id,
      homeTeamId: { ...teamMap[normalize("Escócia")] }.id,
      awayTeamId: { ...teamMap[normalize("Marrocos")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-19T19:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 2,
    },
    {
      id: 30,
      groupId: groupMap[normalize("Grupo C")]?.id,
      homeTeamId: { ...teamMap[normalize("Brasil")] }.id,
      awayTeamId: { ...teamMap[normalize("Haiti")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-19T21:30:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 2,
    },
    {
      id: 31,
      groupId: groupMap[normalize("Grupo D")]?.id,
      homeTeamId: { ...teamMap[normalize("Estados Unidos")] }.id,
      awayTeamId: { ...teamMap[normalize("Austrália")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-19T16:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 2,
    },
    {
      id: 32,
      groupId: groupMap[normalize("Grupo D")]?.id,
      homeTeamId: { ...teamMap[normalize("Turquia")] }.id,
      awayTeamId: { ...teamMap[normalize("Paraguai")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-20T01:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 2,
    },
    {
      id: 33,
      groupId: groupMap[normalize("Grupo E")]?.id,
      homeTeamId: { ...teamMap[normalize("Alemanha")] }.id,
      awayTeamId: { ...teamMap[normalize("Costa do Marfim")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-20T17:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 2,
    },
    {
      id: 34,
      groupId: groupMap[normalize("Grupo E")]?.id,
      homeTeamId: { ...teamMap[normalize("Equador")] }.id,
      awayTeamId: { ...teamMap[normalize("Curaçao")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-20T21:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 2,
    },
    {
      id: 35,
      groupId: groupMap[normalize("Grupo F")]?.id,
      homeTeamId: { ...teamMap[normalize("Holanda")] }.id,
      awayTeamId: { ...teamMap[normalize("Suécia")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-20T14:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 2,
    },
    {
      id: 36,
      groupId: groupMap[normalize("Grupo F")]?.id,
      homeTeamId: { ...teamMap[normalize("Tunísia")] }.id,
      awayTeamId: { ...teamMap[normalize("Japão")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-21T01:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 2,
    },
    {
      id: 37,
      groupId: groupMap[normalize("Grupo G")]?.id,
      homeTeamId: { ...teamMap[normalize("Bélgica")] }.id,
      awayTeamId: { ...teamMap[normalize("Iran")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-21T16:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 2,
    },
    {
      id: 38,
      groupId: groupMap[normalize("Grupo G")]?.id,
      homeTeamId: { ...teamMap[normalize("Nova Zelândia")] }.id,
      awayTeamId: { ...teamMap[normalize("Egito")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-21T22:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 2,
    },
    {
      id: 39,
      groupId: groupMap[normalize("Grupo H")]?.id,
      homeTeamId: { ...teamMap[normalize("Espanha")] }.id,
      awayTeamId: { ...teamMap[normalize("Arábia Saudita")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-21T13:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 2,
    },
    {
      id: 40,
      groupId: groupMap[normalize("Grupo H")]?.id,
      homeTeamId: { ...teamMap[normalize("Uruguai")] }.id,
      awayTeamId: { ...teamMap[normalize("Cabo Verde")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-21T19:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 2,
    },
    {
      id: 41,
      groupId: groupMap[normalize("Grupo I")]?.id,
      homeTeamId: { ...teamMap[normalize("França")] }.id,
      awayTeamId: { ...teamMap[normalize("Iraque")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-22T18:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 2,
    },
    {
      id: 42,
      groupId: groupMap[normalize("Grupo I")]?.id,
      homeTeamId: { ...teamMap[normalize("Noruega")] }.id,
      awayTeamId: { ...teamMap[normalize("Senegal")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-22T21:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 2,
    },
    {
      id: 43,
      groupId: groupMap[normalize("Grupo J")]?.id,
      homeTeamId: { ...teamMap[normalize("Argentina")] }.id,
      awayTeamId: { ...teamMap[normalize("Áustria")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-22T14:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 2,
    },
    {
      id: 44,
      groupId: groupMap[normalize("Grupo J")]?.id,
      homeTeamId: { ...teamMap[normalize("Jordânia")] }.id,
      awayTeamId: { ...teamMap[normalize("Argélia")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-23T00:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 2,
    },
    {
      id: 45,
      groupId: groupMap[normalize("Grupo K")]?.id,
      homeTeamId: { ...teamMap[normalize("Portugal")] }.id,
      awayTeamId: { ...teamMap[normalize("Uzbequistão")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-23T14:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 2,
    },
    {
      id: 46,
      groupId: groupMap[normalize("Grupo K")]?.id,
      homeTeamId: { ...teamMap[normalize("Colômbia")] }.id,
      awayTeamId: { ...teamMap[normalize("Congo")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-23T23:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 2,
    },
    {
      id: 47,
      groupId: groupMap[normalize("Grupo L")]?.id,
      homeTeamId: { ...teamMap[normalize("Inglaterra")] }.id,
      awayTeamId: { ...teamMap[normalize("Gana")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-23T17:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 2,
    },
    {
      id: 48,
      groupId: groupMap[normalize("Grupo L")]?.id,
      homeTeamId: { ...teamMap[normalize("Panamá")] }.id,
      awayTeamId: { ...teamMap[normalize("Croácia")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-23T20:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 2,
    },
  ],
};

export const Round_Three: Round = {
  id: 3,
  matches: [
    {
      id: 49,
      groupId: groupMap[normalize("Grupo A")]?.id,
      homeTeamId: { ...teamMap[normalize("África do Sul")] }.id,
      awayTeamId: { ...teamMap[normalize("Coreia do Sul")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-24T22:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 3,
    },
    {
      id: 50,
      groupId: groupMap[normalize("Grupo A")]?.id,
      homeTeamId: { ...teamMap[normalize("República Tcheca")] }.id,
      awayTeamId: { ...teamMap[normalize("México")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-24T22:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 3,
    },
    {
      id: 51,
      groupId: groupMap[normalize("Grupo B")]?.id,
      homeTeamId: { ...teamMap[normalize("Suíça")] }.id,
      awayTeamId: { ...teamMap[normalize("Canadá")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-24T22:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 3,
    },
    {
      id: 52,
      groupId: groupMap[normalize("Grupo B")]?.id,
      homeTeamId: { ...teamMap[normalize("Bósnia e Herzegovina")] }.id,
      awayTeamId: { ...teamMap[normalize("Catar")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-24T22:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 3,
    },
    {
      id: 53,
      groupId: groupMap[normalize("Grupo C")]?.id,
      homeTeamId: { ...teamMap[normalize("Marrocos")] }.id,
      awayTeamId: { ...teamMap[normalize("Haiti")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-24T19:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 3,
    },
    {
      id: 54,
      groupId: groupMap[normalize("Grupo C")]?.id,
      homeTeamId: { ...teamMap[normalize("Escócia")] }.id,
      awayTeamId: { ...teamMap[normalize("Brasil")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-24T19:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 3,
    },
    {
      id: 55,
      groupId: groupMap[normalize("Grupo D")]?.id,
      homeTeamId: { ...teamMap[normalize("Tunísia")] }.id,
      awayTeamId: { ...teamMap[normalize("Estados Unidos")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-25T23:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 3,
    },
    {
      id: 56,
      groupId: groupMap[normalize("Grupo D")]?.id,
      homeTeamId: { ...teamMap[normalize("Paraguai")] }.id,
      awayTeamId: { ...teamMap[normalize("Austrália")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-25T23:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 3,
    },
    {
      id: 57,
      groupId: groupMap[normalize("Grupo E")]?.id,
      homeTeamId: { ...teamMap[normalize("Equador")] }.id,
      awayTeamId: { ...teamMap[normalize("Alemanha")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-25T17:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 3,
    },
    {
      id: 58,
      groupId: groupMap[normalize("Grupo E")]?.id,
      homeTeamId: { ...teamMap[normalize("Curaçao")] }.id,
      awayTeamId: { ...teamMap[normalize("Costa do Marfim")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-25T17:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 3,
    },
    {
      id: 59,
      groupId: groupMap[normalize("Grupo F")]?.id,
      homeTeamId: { ...teamMap[normalize("Tunísia")] }.id,
      awayTeamId: { ...teamMap[normalize("Holanda")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-25T20:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 3,
    },
    {
      id: 60,
      groupId: groupMap[normalize("Grupo F")]?.id,
      homeTeamId: { ...teamMap[normalize("Japão")] }.id,
      awayTeamId: { ...teamMap[normalize("Suécia")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-25T20:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 3,
    },
    {
      id: 61,
      groupId: groupMap[normalize("Grupo G")]?.id,
      homeTeamId: { ...teamMap[normalize("Egito")] }.id,
      awayTeamId: { ...teamMap[normalize("Iran")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-27T00:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 3,
    },
    {
      id: 62,
      groupId: groupMap[normalize("Grupo G")]?.id,
      homeTeamId: { ...teamMap[normalize("Nova Zelândia")] }.id,
      awayTeamId: { ...teamMap[normalize("Bélgica")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-27T00:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 3,
    },
    {
      id: 63,
      groupId: groupMap[normalize("Grupo H")]?.id,
      homeTeamId: { ...teamMap[normalize("Cabo Verde")] }.id,
      awayTeamId: { ...teamMap[normalize("Arábia Saudita")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-26T21:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 3,
    },
    {
      id: 64,
      groupId: groupMap[normalize("Grupo H")]?.id,
      homeTeamId: { ...teamMap[normalize("Uruguai")] }.id,
      awayTeamId: { ...teamMap[normalize("Espanha")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-26T21:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 3,
    },
    {
      id: 65,
      groupId: groupMap[normalize("Grupo I")]?.id,
      homeTeamId: { ...teamMap[normalize("Senegal")] }.id,
      awayTeamId: { ...teamMap[normalize("Iraque")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-26T16:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 3,
    },
    {
      id: 66,
      groupId: groupMap[normalize("Grupo I")]?.id,
      homeTeamId: { ...teamMap[normalize("Noruega")] }.id,
      awayTeamId: { ...teamMap[normalize("França")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-26T16:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 3,
    },
    {
      id: 67,
      groupId: groupMap[normalize("Grupo J")]?.id,
      homeTeamId: { ...teamMap[normalize("Jordânia")] }.id,
      awayTeamId: { ...teamMap[normalize("Argentina")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-27T23:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 3,
    },
    {
      id: 68,
      groupId: groupMap[normalize("Grupo J")]?.id,
      homeTeamId: { ...teamMap[normalize("Argélia")] }.id,
      awayTeamId: { ...teamMap[normalize("Áustria")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-27T23:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 3,
    },
    {
      id: 69,
      groupId: groupMap[normalize("Grupo K")]?.id,
      homeTeamId: { ...teamMap[normalize("Congo")] }.id,
      awayTeamId: { ...teamMap[normalize("Uzbequistão")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-27T20:30:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 3,
    },
    {
      id: 70,
      groupId: groupMap[normalize("Grupo K")]?.id,
      homeTeamId: { ...teamMap[normalize("Colômbia")] }.id,
      awayTeamId: { ...teamMap[normalize("Portugal")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-27T20:30:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 3,
    },
    {
      id: 71,
      groupId: groupMap[normalize("Grupo L")]?.id,
      homeTeamId: { ...teamMap[normalize("Croácia")] }.id,
      awayTeamId: { ...teamMap[normalize("Gana")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-27T18:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 3,
    },
    {
      id: 72,
      groupId: groupMap[normalize("Grupo L")]?.id,
      homeTeamId: { ...teamMap[normalize("Panamá")] }.id,
      awayTeamId: { ...teamMap[normalize("Inglaterra")] }.id,
      homeTeamGoals: null,
      awayTeamGoals: null,
      date: new Date("2026-06-27T18:00:00Z"),
      stage: TournamentStage.GROUP_STAGE,
      roundId: 3,
    },
  ],
};
